#########################
## Sample Sass Lint File
#########################
files:
  include:
    - 'static/styles/**.scss'
    - 'src/components/**/**.scss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 1
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
